# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000 to be used by Flask
EXPOSE 5000

# Define environment variable for Flask
ENV FLASK_ENV=production

# Run serve_model.py when the container launches
CMD ["python", "serve_model.py"]
